name: giara
base: core20
adopt-info: giara
grade: stable
confinement: strict

slots:
  dbus-giara:
    interface: dbus
    bus: session
    name: org.gabmus.giara

plugs:
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/icons
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/sounds

apps:
  giara:
    command: usr/bin/giara
    command-chain: [ bin/desktop-launch ]
    common-id: org.gabmus.giara
    environment:
      GTK_USE_PORTAL: '1'
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.8/dist-packages:$SNAP/usr/lib/python3.8/site-packages
      GI_TYPELIB_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgtk-3-0:$LD_LIBRARY_PATH
    slots: [ dbus-giara ]
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
      - home
      - network

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/share/xml/iso-codes:
    bind: $SNAP/usr/share/xml/iso-codes
  /usr/share/giara:
    bind: $SNAP/usr/share/giara

parts:
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3
      - libgtk2.0-0
      - libcanberra-gtk3-module

  libhandy:
    source: https://gitlab.gnome.org/GNOME/libhandy.git
    source-tag: '1.0.1'
    plugin: meson
    meson-parameters:
      - '-Dglade_catalog=disabled'
      - '-Dtests=false'
      - '-Dexamples=false'
      - --prefix=/usr
    build-packages:
      - debhelper-compat
      - dh-sequence-gir
      - gtk-doc-tools
      - libgirepository1.0-dev
      - libgladeui-dev
      - libglib2.0-doc
      - libgnome-desktop-3-dev
      - libgtk-3-doc
      - libgtk-3-dev
      - libxml2-utils
      - pkg-config
      - valac

  giara:
    after:
      - desktop-gtk3
      - libhandy
    source: https://gitlab.gnome.org/World/giara.git
    source-tag: '0.2'
    plugin: meson
    parse-info: [ usr/share/metainfo/org.gabmus.giara.appdata.xml ]
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - appstream
      - cmake
      - gettext
      - libgirepository1.0-dev
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - python3-dateutil
      - gir1.2-gtk-3.0
      - gir1.2-webkit2-4.0
      - gir1.2-gtksource-4
      - gir1.2-gdkpixbuf-2.0
    override-build: |
      _version="$(git describe --tags | cut -d_ -f2)"
      snapcraftctl set-version "${_version}-snap1"
      snapcraftctl build
      python3 -m pip install --upgrade requests -t "${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8/dist-packages"
      python3 -m pip install --upgrade beautifulsoup4 -t "${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8/dist-packages"
      python3 -m pip install --upgrade Pillow -t "${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8/dist-packages"
      python3 -m pip install --upgrade praw -t "${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8/dist-packages"
      python3 -m pip install --upgrade mistune -t "${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8/dist-packages"
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/org.gabmus.giara.svg|g' $SNAPCRAFT_PRIME/usr/share/applications/org.gabmus.giara.desktop
